services:
  janitor-ui:
    image: ghcr.io/nuken/docker-janitor:latest
    container_name: janitor-ui
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
